#!/usr/bin/env python3
"""app/my-hub.css: generated from the approved mock-up, and kept honest.

The file is produced by Hub/My-Hub-Home-2026-10/tools/port_mockup_css.py in
Cowork-OS. These checks keep it fit for a live Hub page whoever touches it:
every rule is scoped to My Hub (a stray rule restyles all 60-odd Hub pages
the moment it lands), none of the retired palette, nothing under 12px
(the spec's design bar), and keyframes that cannot collide with the theme's.

    python3 test_my_hub_css.py
"""
import os
import re
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
CSS = os.path.join(HERE, "app", "my-hub.css")
RETIRED = ("#faf8f3", "#6e6553", "#5e3a4c", "#b06a4e")


def blocks(css):
    out, i, n = [], 0, len(css)
    while i < n:
        j = css.find("{", i)
        if j == -1:
            break
        depth, k = 1, j + 1
        while depth and k < n:
            if css[k] == "{":
                depth += 1
            elif css[k] == "}":
                depth -= 1
            k += 1
        out.append((css[i:j].strip(), css[j + 1:k - 1]))
        i = k
    return out


class MyHubCss(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with open(CSS, encoding="utf-8") as f:
            cls.raw = f.read()
        cls.css = re.sub(r"/\*.*?\*/", "", cls.raw, flags=re.S)

    def test_generated_header(self):
        self.assertTrue(self.raw.startswith("/* GENERATED by "), "regenerate with port_mockup_css.py")

    def selectors(self):
        for prelude, body in blocks(self.css):
            if prelude.startswith("@keyframes"):
                continue
            if prelude.startswith("@media"):
                for p, _ in blocks(body):
                    yield p
            else:
                yield prelude

    def test_every_rule_is_scoped_to_my_hub(self):
        n = 0
        for prelude in self.selectors():
            for s in prelude.split(","):
                s = s.strip()
                n += 1
                self.assertTrue(s == "#msh-my-hub" or s.startswith(".msh #msh-my-hub"), "unscoped selector: %r" % s)
        self.assertGreater(n, 200)

    def test_no_retired_palette(self):
        low = self.css.lower()
        for hexv in RETIRED:
            self.assertNotIn(hexv, low, "retired colour %s" % hexv)

    def test_twelve_pixel_minimum(self):
        for m in re.finditer(r"font-size:\s*(\d+(?:\.\d+)?)px", self.css):
            self.assertGreaterEqual(float(m.group(1)), 12, m.group(0))

    def test_keyframes_are_prefixed(self):
        names = re.findall(r"@keyframes\s+([A-Za-z0-9_-]+)", self.css)
        self.assertTrue(names)
        for n in names:
            self.assertTrue(n.startswith("mhx"), n)
        for m in re.finditer(r"animation(?:-name)?:\s*([A-Za-z][A-Za-z0-9_-]*)", self.css):
            if m.group(1) != "none":
                self.assertIn(m.group(1), names, m.group(0))

    def test_dark_backgrounds_set_a_light_colour(self):
        """A dark brand surface must say its own light text colour: the mock-up's
        'a{color:inherit}' otherwise lets dark ink land on navy (search results)."""
        root = re.search(r"#msh-my-hub\{([^}]*)\}", self.css).group(1)
        var = dict(re.findall(r"(--[a-z0-9-]+):(#[0-9A-Fa-f]{6})(?![0-9A-Fa-f])", root))
        # Rules that only recolour a surface whose base rule already sets the light
        # text colour (the cascade keeps it), or whose element carries no text.
        NO_TEXT_OR_INHERITS = {".ib .dot", ".days.soon", ".tile:nth-child(even) .ti", ".tip .pips i.on"}
        dark = {"#0b1c33", "#14304f", "#4a1526", "#6b2a34"}

        def resolve(v):
            m = re.fullmatch(r"var\((--[a-z0-9-]+)\)", v.strip())
            return (var.get(m.group(1), "") if m else v.strip()).lower()

        def light(c):
            m = re.fullmatch(r"#([0-9a-f]{3}|[0-9a-f]{6})", c)
            if not m:
                return False
            h = m.group(1)
            if len(h) == 3:
                h = "".join(ch * 2 for ch in h)
            r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
            return 0.299 * r + 0.587 * g + 0.114 * b > 170

        def rules():
            for prelude, body in blocks(self.css):
                if prelude.startswith("@keyframes"):
                    continue
                if prelude.startswith("@media"):
                    for p, b in blocks(body):
                        yield p, b
                else:
                    yield prelude, body

        checked = 0
        for prelude, body in rules():
            d = dict((k.strip(), v.strip()) for k, v in (x.split(":", 1) for x in body.split(";") if ":" in x))
            bg = d.get("background") or d.get("background-color") or ""
            if not bg or resolve(bg.split()[0]) not in dark:
                continue
            if prelude.replace(".msh #msh-my-hub ", "") in NO_TEXT_OR_INHERITS:
                continue
            checked += 1
            col = resolve(d.get("color", "").replace("!important", ""))
            self.assertTrue(light(col), "dark surface without a light colour: %s -> %r" % (prelude[:80], d.get("color")))
        self.assertGreater(len(var), 10, 'var map empty')
        self.assertGreaterEqual(checked, 10)  # v4 has fewer separate dark rules than v2; the stale white wn-strip override (2 dark rules) was removed 06/10
        print('dark rules checked:', checked)

    def test_no_imports_or_remote_urls(self):
        self.assertNotIn("@import", self.css)
        for u in re.findall(r"url\(\s*['\"]?(https?:[^)'\"]*)", self.css):
            self.assertTrue(u.startswith("https://medsalesintelligencehub.co.uk/wp-content/uploads/"), u)


if __name__ == "__main__":
    unittest.main(verbosity=1)
