// Builds www/app.js from src/. Writes src/config.js first from:
//   ../alerts/config.json   Supabase URL, publishable key, speciality list (generated
//                           by scripts/push_alerts.py build-config; public values only)
//   env                     REVENUECAT_IOS_KEY, REVENUECAT_ANDROID_KEY (RevenueCat
//                           public SDK keys; blank = no subscribe option shown)
// Nothing secret is ever bundled: these are all public client keys.
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';

const alerts = JSON.parse(readFileSync(new URL('../alerts/config.json', import.meta.url), 'utf8'));
const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8'));
const HUB = alerts.hubOrigin;

const config = {
  version: pkg.version,
  supabaseUrl: alerts.supabaseUrl,
  supabaseAnonKey: alerts.supabaseAnonKey,
  hubLinkUrl: HUB + '/medical-sales-hub/live-desk-app/?from=app',
  privacyUrl: HUB + '/live-desk-app-privacy/',
  termsUrl: 'https://www.apple.com/legal/internet-services/itunes/dev/stdeula/',
  supportUrl: HUB + '/live-desk-app-support/',
  revenueCatKey: { ios: process.env.REVENUECAT_IOS_KEY || '', android: process.env.REVENUECAT_ANDROID_KEY || '' },
  specialities: alerts.specialities,
};
writeFileSync(new URL('./src/config.js', import.meta.url),
  '// GENERATED by build.mjs. Edit build.mjs or ../alerts/config.json, not this file.\n' +
  'export const CONFIG = ' + JSON.stringify(config, null, 2) + ';\n');

await build({
  entryPoints: ['src/main.js'], bundle: true, minify: true, format: 'esm', target: ['safari15', 'chrome100'],
  outfile: 'www/app.js', logLevel: 'info',
  alias: { 'firebase/messaging': './src/firebase-web-stub.js' },
});
